django-model-practice/config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('phonebook/', include(('phonebook.urls','Phonebook'),namespace="pb")),
]

django-model-practice/phonebook/urls.py
from django.urls import path,include
from phonebook import views

urlpatterns = [
    path('index/', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('delete/', views.delete, name='delete'),
    path('detail/<idx>', views.detail, name='detail'),
    path('update/', views.update, name='update'),
]

django-model-practice/phonebook/models.py
from django.db import models

# Create your models here.

class Phonebook(models.Model):
    fname=models.CharField(max_length=50,null=False)
    lname=models.CharField(max_length=50,null=False)
    phone=models.CharField(max_length=20)
    email=models.EmailField()
    address=models.CharField(max_length=100)
    birthday=models.DateField()

django-model-practice/phonebook/views.py
from django.shortcuts import render
from .models import Phonebook

# Create your views here.
# def index(request):
#     return render(request,'PBook/index.html')
def index(request):
    members = Phonebook.objects.all()
    context={'Phonebook' : members} # 공백 중요
    return render(request,'PBook/index.html',context)

def add(request):
    return render(request,'PBook/add.html')

def delete(request):
    return render(request,'PBook/delete.html')

def detail(request,idx):
    userinfo = Phonebook.objects.values('id','fname','lname','address','email','phone','birthday').get(id=idx)
    context={ 'Phonebook' : userinfo }
    return render(request,'PBook/detail.html',context)

def update(request):
    return render(request,'PBook/update.html')

django-model-practice/templates/pbook/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TEST</title>
</head>
<body>
    <div>
        <h1>This is the ADD page in PBook.</h1>
    </div>
</body>
</html>

django-model-practice/templates/pbook/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TEST</title>
</head>
<body>
    <div>
        <h1>This is the DELETE page in PBook.</h1>
    </div>
</body>
</html>

django-model-practice/templates/pbook/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TEST</title>
</head>
<style>
    footer {
      text-align: center;
      padding: 3px;
      background-color: DarkSalmon;
      color: white;
    }
</style>
<body>
    <div>
        <h1>This is the DETAIL page in PBook.</h1>
        {% for key,value in Phonebook.items %}
            <li><b>{{key}}</b> : {{value}}</li><br>
        {% endfor %}
    </div>
    <div>
        {{Phonebook.birthday | date:'Y M D'}}<br>
        {{Phonebook.birthday | date:'y m y'}}<br>
        {{Phonebook.birthday | date:'Y년-m월-d일'}}<br>
    </div>
    <footer>
        <p>Author: Hege Refsnes<br>
        <a href="mailto:hege@example.com">hege@example.com</a></p>
      </footer>

</body>
</html>

django-model-practice/templates/pbook/index.html
{% extends 'config/form.html' %}
{% block center %} <!-- center는 form.html 과 동일하게-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TEST</title>
</head>
<style>
    footer {
      text-align: center;
      padding: 3px;
      background-color: DarkSalmon;
      color: white;
    }
</style>
<body>
    <div>
        <h1>This is the INDEX page in PBook.</h1>
    </div>
    <div>
        {% for value in Phonebook %}
            <li><a href="{% url 'pb:detail' value.id %}">{{value.fname}}</a> : {{ value.phone }}</li>
        {% endfor %}
        <hr>
       </div>
       <footer>
        <p>Author: Kevin Kim<br>
        <a href="mailto:admin@labs.local">admin@labs.local</a></p>
      </footer>
</body>
</html>
{% endblock center %}

django-model-practice/templates/pbook/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TEST</title>
</head>
<body>
    <div>
        <h1>This is the UPDATE page in PBook.</h1>
    </div>
</body>
</html>